[package]
name = "ydb-unofficial"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
keywords = ["database","db","ydb"]
description = "Rust grpc bindings for YDB (unofficial)"
repository = "https://hub.mos.ru/bool.rus/ydb-unofficial.git"

[lib]
doctest = true 


[dependencies]
tonic = { versoin = "0.9", features = ["tls-roots"] }
tokio = { version = "1.27.0", features = ["full"] }
ydb-grpc-bindings = "0.0.1"
prost = "0.11.2"
ctor = "0.2.0"
deadpool = "0.9.5"
async-trait = "0.1.68"
tower = { version = "0.4.13", features = ["balance"] }
rand = "0.8.5"
log = "0.4.17"
simplelog = "0.12.1"
thiserror = "1.0.40"

[build-dependencies]
tonic-build = "0.9"
