[package]
name = "ydb-unofficial"
version = "0.2.1"
edition = "2021"
license = "Apache-2.0"
keywords = ["database","db","ydb"]
description = "Unofficial Ydb client library written on rust"
repository = "https://hub.mos.ru/bool.rus/ydb-unofficial.git"

[lib]
doctest = true 


[dependencies]
tonic = { version = "0.9.2", features = ["tls-roots"] }
tokio = { version = "1.27.0", features = ["full"] }
ydb-grpc-bindings = "0.0.1"
prost = "0.11.2"
ctor = "0.2.0"
deadpool = "0.9.5"
async-trait = "0.1.68"
tower = "0.4.13"
rand = "0.8.5"
log = "0.4.17"
thiserror = "1.0.40"

# service account auth
yandex-cloud = "2023.6.13"
jwt-simple = { git = "https://github.com/bool-rus/rust-jwt-simple.git", branch = "bugfix/PS256-salt-len" }
serde = "1.0.171"
serde_json = "1.0.102"
