/// A lot of autogenerated (with `tonic`) grpc-types from ydb .proto files
pub use ydb_grpc_bindings::generated;
pub use tonic;
/// Ascii encoded value to use in grpc metadata
pub type AsciiValue = tonic::metadata::MetadataValue<tonic::metadata::Ascii>;
